steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sharingsongs:$SHORT_SHA', '.']
  # Run unit tests
  - name: gcr.io/$PROJECT_ID/sharingsongs:$SHORT_SHA
    entrypoint: python
    args: ["-m","pytest","unit_tests.py"]
  # Push docker image and save image digest for kritis check
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sharingsongs:$SHORT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'sharingsongs',
         '--image', 'gcr.io/$PROJECT_ID/sharingsongs:$SHORT_SHA',
         '--region', 'southamerica-east1',
         '--platform', 'managed',
         '--allow-unauthenticated']
